// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o1vPdgLXqG8oxG6Tov2xRt
// Component: 243C3rS9tg
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_empty_project_mobile_first.module.css"; // plasmic-import: o1vPdgLXqG8oxG6Tov2xRt/projectcss
import * as sty from "./Plasmic_8.module.css"; // plasmic-import: 243C3rS9tg/css
import BaseFabExtendedAtomsDiamondIcon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond"; // plasmic-import: mlbS78wvC-2/icon
import BaseFabExtendedAtomsDiamond2Icon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond2"; // plasmic-import: atsv3shmpol/icon
import MaskIcon from "./icons/PlasmicIcon__Mask"; // plasmic-import: PW6nB-ZdXb6/icon

export const Plasmic_8__VariantProps = new Array();

export const Plasmic_8__ArgProps = new Array();

function Plasmic_8__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"iPhone863"}
            data-plasmic-override={overrides.iPhone863}
            className={classNames(defaultcss.all, sty.iPhone863)}
          >
            {false ? (
              <div
                data-plasmic-name={"icons3"}
                data-plasmic-override={overrides.icons3}
                className={classNames(defaultcss.all, sty.icons3)}
              >
                <div
                  data-plasmic-name={"overflow3"}
                  data-plasmic-override={overrides.overflow3}
                  className={classNames(defaultcss.all, sty.overflow3)}
                />

                <div
                  data-plasmic-name={"icon33"}
                  data-plasmic-override={overrides.icon33}
                  className={classNames(defaultcss.all, sty.icon33)}
                />

                <div
                  data-plasmic-name={"icon23"}
                  data-plasmic-override={overrides.icon23}
                  className={classNames(defaultcss.all, sty.icon23)}
                />

                <div
                  data-plasmic-name={"icon13"}
                  data-plasmic-override={overrides.icon13}
                  className={classNames(defaultcss.all, sty.icon13)}
                />
              </div>
            ) : null}

            <div
              data-plasmic-name={"buttons5"}
              data-plasmic-override={overrides.buttons5}
              className={classNames(defaultcss.all, sty.buttons5)}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape4"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape4
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape4
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle4"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle4
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle4
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare4"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare4
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare4
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle10"}
                        data-plasmic-override={overrides.rectangle10}
                        className={classNames(defaultcss.all, sty.rectangle10)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamondIcon
                    className={classNames(defaultcss.all, sty.svg__gr7SY)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle5"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle5}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle5
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle11"}
                    data-plasmic-override={overrides.rectangle11}
                    className={classNames(defaultcss.all, sty.rectangle11)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label5"}
                data-plasmic-override={overrides.label5}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label5
                )}
              >
                {"Create your account"}
              </div>
            </div>

            <div
              data-plasmic-name={"buttons6"}
              data-plasmic-override={overrides.buttons6}
              className={classNames(defaultcss.all, sty.buttons6)}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape5"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape5
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape5
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle5"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle5
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle5
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare5"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare5
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare5
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle12"}
                        data-plasmic-override={overrides.rectangle12}
                        className={classNames(defaultcss.all, sty.rectangle12)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamond2Icon
                    className={classNames(defaultcss.all, sty.svg__x30XC)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle6"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle6}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle6
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle13"}
                    data-plasmic-override={overrides.rectangle13}
                    className={classNames(defaultcss.all, sty.rectangle13)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label6"}
                data-plasmic-override={overrides.label6}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label6
                )}
              >
                {"SIGN IN"}
              </div>
            </div>

            <div
              data-plasmic-name={"landingPage010212"}
              data-plasmic-override={overrides.landingPage010212}
              className={classNames(defaultcss.all, sty.landingPage010212)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__d43T0
              )}
            >
              {"We listen, we care."}
            </div>

            <div
              data-plasmic-name={"asset11"}
              data-plasmic-override={overrides.asset11}
              className={classNames(defaultcss.all, sty.asset11)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__m7Mt7
              )}
            >
              {"*alpha"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__om1Ki
              )}
            >
              {"What is April Cares?"}
            </div>

            {false ? (
              <div
                data-plasmic-name={"ωAtomsSystemBarDark3"}
                data-plasmic-override={overrides.ωAtomsSystemBarDark3}
                className={classNames(defaultcss.all, sty.ωAtomsSystemBarDark3)}
              >
                <div
                  data-plasmic-name={"rectangle14"}
                  data-plasmic-override={overrides.rectangle14}
                  className={classNames(defaultcss.all, sty.rectangle14)}
                />

                <MaskIcon
                  className={classNames(defaultcss.all, sty.svg__aGr2C)}
                  role={"img"}
                />
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "iPhone863",
    "icons3",
    "overflow3",
    "icon33",
    "icon23",
    "icon13",
    "buttons5",
    "baseFabExtendedFabExtendedMasterShape4",
    "baseFabExtendedAtomsSquircle4",
    "baseSurfaceShapeAtomsSquare4",
    "rectangle10",
    "baseFabExtendedAtomsCircle5",
    "rectangle11",
    "label5",
    "buttons6",
    "baseFabExtendedFabExtendedMasterShape5",
    "baseFabExtendedAtomsSquircle5",
    "baseSurfaceShapeAtomsSquare5",
    "rectangle12",
    "baseFabExtendedAtomsCircle6",
    "rectangle13",
    "label6",
    "landingPage010212",
    "asset11",
    "ωAtomsSystemBarDark3",
    "rectangle14"
  ],

  iPhone863: [
    "iPhone863",
    "icons3",
    "overflow3",
    "icon33",
    "icon23",
    "icon13",
    "buttons5",
    "baseFabExtendedFabExtendedMasterShape4",
    "baseFabExtendedAtomsSquircle4",
    "baseSurfaceShapeAtomsSquare4",
    "rectangle10",
    "baseFabExtendedAtomsCircle5",
    "rectangle11",
    "label5",
    "buttons6",
    "baseFabExtendedFabExtendedMasterShape5",
    "baseFabExtendedAtomsSquircle5",
    "baseSurfaceShapeAtomsSquare5",
    "rectangle12",
    "baseFabExtendedAtomsCircle6",
    "rectangle13",
    "label6",
    "landingPage010212",
    "asset11",
    "ωAtomsSystemBarDark3",
    "rectangle14"
  ],

  icons3: ["icons3", "overflow3", "icon33", "icon23", "icon13"],
  overflow3: ["overflow3"],
  icon33: ["icon33"],
  icon23: ["icon23"],
  icon13: ["icon13"],
  buttons5: [
    "buttons5",
    "baseFabExtendedFabExtendedMasterShape4",
    "baseFabExtendedAtomsSquircle4",
    "baseSurfaceShapeAtomsSquare4",
    "rectangle10",
    "baseFabExtendedAtomsCircle5",
    "rectangle11",
    "label5"
  ],

  baseFabExtendedFabExtendedMasterShape4: [
    "baseFabExtendedFabExtendedMasterShape4",
    "baseFabExtendedAtomsSquircle4",
    "baseSurfaceShapeAtomsSquare4",
    "rectangle10",
    "baseFabExtendedAtomsCircle5",
    "rectangle11"
  ],

  baseFabExtendedAtomsSquircle4: [
    "baseFabExtendedAtomsSquircle4",
    "baseSurfaceShapeAtomsSquare4",
    "rectangle10"
  ],

  baseSurfaceShapeAtomsSquare4: ["baseSurfaceShapeAtomsSquare4", "rectangle10"],
  rectangle10: ["rectangle10"],
  baseFabExtendedAtomsCircle5: ["baseFabExtendedAtomsCircle5", "rectangle11"],
  rectangle11: ["rectangle11"],
  label5: ["label5"],
  buttons6: [
    "buttons6",
    "baseFabExtendedFabExtendedMasterShape5",
    "baseFabExtendedAtomsSquircle5",
    "baseSurfaceShapeAtomsSquare5",
    "rectangle12",
    "baseFabExtendedAtomsCircle6",
    "rectangle13",
    "label6"
  ],

  baseFabExtendedFabExtendedMasterShape5: [
    "baseFabExtendedFabExtendedMasterShape5",
    "baseFabExtendedAtomsSquircle5",
    "baseSurfaceShapeAtomsSquare5",
    "rectangle12",
    "baseFabExtendedAtomsCircle6",
    "rectangle13"
  ],

  baseFabExtendedAtomsSquircle5: [
    "baseFabExtendedAtomsSquircle5",
    "baseSurfaceShapeAtomsSquare5",
    "rectangle12"
  ],

  baseSurfaceShapeAtomsSquare5: ["baseSurfaceShapeAtomsSquare5", "rectangle12"],
  rectangle12: ["rectangle12"],
  baseFabExtendedAtomsCircle6: ["baseFabExtendedAtomsCircle6", "rectangle13"],
  rectangle13: ["rectangle13"],
  label6: ["label6"],
  landingPage010212: ["landingPage010212"],
  asset11: ["asset11"],
  ωAtomsSystemBarDark3: ["ωAtomsSystemBarDark3", "rectangle14"],
  rectangle14: ["rectangle14"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_8__ArgProps,
      internalVariantPropNames: Plasmic_8__VariantProps
    });

    return Plasmic_8__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_8";
  } else {
    func.displayName = `Plasmic_8.${nodeName}`;
  }
  return func;
}

export const Plasmic_8 = Object.assign(
  // Top-level Plasmic_8 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iPhone863: makeNodeComponent("iPhone863"),
    icons3: makeNodeComponent("icons3"),
    overflow3: makeNodeComponent("overflow3"),
    icon33: makeNodeComponent("icon33"),
    icon23: makeNodeComponent("icon23"),
    icon13: makeNodeComponent("icon13"),
    buttons5: makeNodeComponent("buttons5"),
    baseFabExtendedFabExtendedMasterShape4: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape4"
    ),

    baseFabExtendedAtomsSquircle4: makeNodeComponent(
      "baseFabExtendedAtomsSquircle4"
    ),

    baseSurfaceShapeAtomsSquare4: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare4"
    ),

    rectangle10: makeNodeComponent("rectangle10"),
    baseFabExtendedAtomsCircle5: makeNodeComponent(
      "baseFabExtendedAtomsCircle5"
    ),

    rectangle11: makeNodeComponent("rectangle11"),
    label5: makeNodeComponent("label5"),
    buttons6: makeNodeComponent("buttons6"),
    baseFabExtendedFabExtendedMasterShape5: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape5"
    ),

    baseFabExtendedAtomsSquircle5: makeNodeComponent(
      "baseFabExtendedAtomsSquircle5"
    ),

    baseSurfaceShapeAtomsSquare5: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare5"
    ),

    rectangle12: makeNodeComponent("rectangle12"),
    baseFabExtendedAtomsCircle6: makeNodeComponent(
      "baseFabExtendedAtomsCircle6"
    ),

    rectangle13: makeNodeComponent("rectangle13"),
    label6: makeNodeComponent("label6"),
    landingPage010212: makeNodeComponent("landingPage010212"),
    asset11: makeNodeComponent("asset11"),
    ωAtomsSystemBarDark3: makeNodeComponent("ωAtomsSystemBarDark3"),
    rectangle14: makeNodeComponent("rectangle14"),
    // Metadata about props expected for Plasmic_8
    internalVariantProps: Plasmic_8__VariantProps,
    internalArgProps: Plasmic_8__ArgProps
  }
);

export default Plasmic_8;
/* prettier-ignore-end */
