// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o1vPdgLXqG8oxG6Tov2xRt
// Component: mmTBH0ICkM
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_empty_project_mobile_first.module.css"; // plasmic-import: o1vPdgLXqG8oxG6Tov2xRt/projectcss
import * as sty from "./Plasmic_5.module.css"; // plasmic-import: mmTBH0ICkM/css
import Ellipse13Icon from "./icons/PlasmicIcon__Ellipse13"; // plasmic-import: ZZCbZ7-sQtPl/icon
import BaseFabExtendedAtomsDiamondIcon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond"; // plasmic-import: mlbS78wvC-2/icon
import SurfaceIcon from "./icons/PlasmicIcon__Surface"; // plasmic-import: loa_NOPfr2n6/icon
import Ellipse9Icon from "./icons/PlasmicIcon__Ellipse9"; // plasmic-import: _fGxh-WhUNmF/icon
import MaskIcon from "./icons/PlasmicIcon__Mask"; // plasmic-import: PW6nB-ZdXb6/icon

export const Plasmic_5__VariantProps = new Array();

export const Plasmic_5__ArgProps = new Array();

function Plasmic_5__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"iPhone848"}
            data-plasmic-override={overrides.iPhone848}
            className={classNames(defaultcss.all, sty.iPhone848)}
          >
            <Ellipse13Icon
              className={classNames(defaultcss.all, sty.svg__b9Pfe)}
              role={"img"}
            />

            {false ? (
              <div
                data-plasmic-name={"icons8"}
                data-plasmic-override={overrides.icons8}
                className={classNames(defaultcss.all, sty.icons8)}
              >
                <div
                  data-plasmic-name={"overflow8"}
                  data-plasmic-override={overrides.overflow8}
                  className={classNames(defaultcss.all, sty.overflow8)}
                />

                <div
                  data-plasmic-name={"icon38"}
                  data-plasmic-override={overrides.icon38}
                  className={classNames(defaultcss.all, sty.icon38)}
                />

                <div
                  data-plasmic-name={"icon28"}
                  data-plasmic-override={overrides.icon28}
                  className={classNames(defaultcss.all, sty.icon28)}
                />

                <div
                  data-plasmic-name={"icon18"}
                  data-plasmic-override={overrides.icon18}
                  className={classNames(defaultcss.all, sty.icon18)}
                />
              </div>
            ) : null}

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__bjMHs
              )}
            >
              {"Providing you support that fits"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___0Lr6
              )}
            >
              {
                "Connect privately with a qualified therapist who listens and guides you, without judging*"
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__lSrq0
              )}
            >
              {"*only for Alpha users"}
            </div>

            <a
              data-plasmic-name={"buttons11"}
              data-plasmic-override={overrides.buttons11}
              className={classNames(defaultcss.all, sty.buttons11)}
              href={"/6"}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape9"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape9
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape9
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle9"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle9
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle9
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare9"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare9
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare9
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle27"}
                        data-plasmic-override={overrides.rectangle27}
                        className={classNames(defaultcss.all, sty.rectangle27)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamondIcon
                    className={classNames(defaultcss.all, sty.svg__oiBiy)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle10"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle10}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle10
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle28"}
                    data-plasmic-override={overrides.rectangle28}
                    className={classNames(defaultcss.all, sty.rectangle28)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label11"}
                data-plasmic-override={overrides.label11}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label11
                )}
              >
                {"Next"}
              </div>
            </a>

            <p.Stack
              as={"div"}
              data-plasmic-name={"group442"}
              data-plasmic-override={overrides.group442}
              hasGap={true}
              className={classNames(defaultcss.all, sty.group442)}
            >
              <div
                data-plasmic-name={"frame12"}
                data-plasmic-override={overrides.frame12}
                className={classNames(defaultcss.all, sty.frame12)}
              />

              <div
                data-plasmic-name={"group422"}
                data-plasmic-override={overrides.group422}
                className={classNames(defaultcss.all, sty.group422)}
              />

              <div
                data-plasmic-name={"frame22"}
                data-plasmic-override={overrides.frame22}
                className={classNames(defaultcss.all, sty.frame22)}
              />
            </p.Stack>

            <div
              data-plasmic-name={"iconBack2"}
              data-plasmic-override={overrides.iconBack2}
              className={classNames(defaultcss.all, sty.iconBack2)}
            >
              <div
                data-plasmic-name={"icroundKeyboardBackspace2"}
                data-plasmic-override={overrides.icroundKeyboardBackspace2}
                className={classNames(
                  defaultcss.all,
                  sty.icroundKeyboardBackspace2
                )}
              />
            </div>

            <a
              data-plasmic-name={"buttons12"}
              data-plasmic-override={overrides.buttons12}
              className={classNames(defaultcss.all, sty.buttons12)}
              href={"/6"}
            >
              <SurfaceIcon
                className={classNames(defaultcss.all, sty.svg__zIkC)}
                role={"img"}
              />

              <div
                data-plasmic-name={"label12"}
                data-plasmic-override={overrides.label12}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label12
                )}
              >
                {"Skip"}
              </div>
            </a>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__vexve
              )}
            >
              {"1"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___6Hx1M
              )}
            >
              {"2"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wwGj2
              )}
            >
              {"3"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___0NEv5
              )}
            >
              {"4"}
            </div>

            <Ellipse9Icon
              className={classNames(defaultcss.all, sty.svg__aYNoX)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__aNw6
              )}
            >
              {"Exploration Journey"}
            </div>

            <Ellipse9Icon
              className={classNames(defaultcss.all, sty.svg___1S3W8)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__jrs8B
              )}
            >
              {"Therapy session"}
            </div>

            <Ellipse9Icon
              className={classNames(defaultcss.all, sty.svg__bWHeZ)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__skwt
              )}
            >
              {"Selfcare"}
            </div>

            <Ellipse9Icon
              className={classNames(defaultcss.all, sty.svg___1HeD6)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xyn6K
              )}
            >
              {"Feedback"}
            </div>

            <div
              data-plasmic-name={"landingPage010213"}
              data-plasmic-override={overrides.landingPage010213}
              className={classNames(defaultcss.all, sty.landingPage010213)}
            />

            {false ? (
              <div
                data-plasmic-name={"ωAtomsSystemBarDark8"}
                data-plasmic-override={overrides.ωAtomsSystemBarDark8}
                className={classNames(defaultcss.all, sty.ωAtomsSystemBarDark8)}
              >
                <div
                  data-plasmic-name={"rectangle29"}
                  data-plasmic-override={overrides.rectangle29}
                  className={classNames(defaultcss.all, sty.rectangle29)}
                />

                <MaskIcon
                  className={classNames(defaultcss.all, sty.svg__zlLfb)}
                  role={"img"}
                />
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "iPhone848",
    "icons8",
    "overflow8",
    "icon38",
    "icon28",
    "icon18",
    "buttons11",
    "baseFabExtendedFabExtendedMasterShape9",
    "baseFabExtendedAtomsSquircle9",
    "baseSurfaceShapeAtomsSquare9",
    "rectangle27",
    "baseFabExtendedAtomsCircle10",
    "rectangle28",
    "label11",
    "group442",
    "frame12",
    "group422",
    "frame22",
    "iconBack2",
    "icroundKeyboardBackspace2",
    "buttons12",
    "label12",
    "landingPage010213",
    "ωAtomsSystemBarDark8",
    "rectangle29"
  ],

  iPhone848: [
    "iPhone848",
    "icons8",
    "overflow8",
    "icon38",
    "icon28",
    "icon18",
    "buttons11",
    "baseFabExtendedFabExtendedMasterShape9",
    "baseFabExtendedAtomsSquircle9",
    "baseSurfaceShapeAtomsSquare9",
    "rectangle27",
    "baseFabExtendedAtomsCircle10",
    "rectangle28",
    "label11",
    "group442",
    "frame12",
    "group422",
    "frame22",
    "iconBack2",
    "icroundKeyboardBackspace2",
    "buttons12",
    "label12",
    "landingPage010213",
    "ωAtomsSystemBarDark8",
    "rectangle29"
  ],

  icons8: ["icons8", "overflow8", "icon38", "icon28", "icon18"],
  overflow8: ["overflow8"],
  icon38: ["icon38"],
  icon28: ["icon28"],
  icon18: ["icon18"],
  buttons11: [
    "buttons11",
    "baseFabExtendedFabExtendedMasterShape9",
    "baseFabExtendedAtomsSquircle9",
    "baseSurfaceShapeAtomsSquare9",
    "rectangle27",
    "baseFabExtendedAtomsCircle10",
    "rectangle28",
    "label11"
  ],

  baseFabExtendedFabExtendedMasterShape9: [
    "baseFabExtendedFabExtendedMasterShape9",
    "baseFabExtendedAtomsSquircle9",
    "baseSurfaceShapeAtomsSquare9",
    "rectangle27",
    "baseFabExtendedAtomsCircle10",
    "rectangle28"
  ],

  baseFabExtendedAtomsSquircle9: [
    "baseFabExtendedAtomsSquircle9",
    "baseSurfaceShapeAtomsSquare9",
    "rectangle27"
  ],

  baseSurfaceShapeAtomsSquare9: ["baseSurfaceShapeAtomsSquare9", "rectangle27"],
  rectangle27: ["rectangle27"],
  baseFabExtendedAtomsCircle10: ["baseFabExtendedAtomsCircle10", "rectangle28"],
  rectangle28: ["rectangle28"],
  label11: ["label11"],
  group442: ["group442", "frame12", "group422", "frame22"],
  frame12: ["frame12"],
  group422: ["group422"],
  frame22: ["frame22"],
  iconBack2: ["iconBack2", "icroundKeyboardBackspace2"],
  icroundKeyboardBackspace2: ["icroundKeyboardBackspace2"],
  buttons12: ["buttons12", "label12"],
  label12: ["label12"],
  landingPage010213: ["landingPage010213"],
  ωAtomsSystemBarDark8: ["ωAtomsSystemBarDark8", "rectangle29"],
  rectangle29: ["rectangle29"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_5__ArgProps,
      internalVariantPropNames: Plasmic_5__VariantProps
    });

    return Plasmic_5__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_5";
  } else {
    func.displayName = `Plasmic_5.${nodeName}`;
  }
  return func;
}

export const Plasmic_5 = Object.assign(
  // Top-level Plasmic_5 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iPhone848: makeNodeComponent("iPhone848"),
    icons8: makeNodeComponent("icons8"),
    overflow8: makeNodeComponent("overflow8"),
    icon38: makeNodeComponent("icon38"),
    icon28: makeNodeComponent("icon28"),
    icon18: makeNodeComponent("icon18"),
    buttons11: makeNodeComponent("buttons11"),
    baseFabExtendedFabExtendedMasterShape9: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape9"
    ),

    baseFabExtendedAtomsSquircle9: makeNodeComponent(
      "baseFabExtendedAtomsSquircle9"
    ),

    baseSurfaceShapeAtomsSquare9: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare9"
    ),

    rectangle27: makeNodeComponent("rectangle27"),
    baseFabExtendedAtomsCircle10: makeNodeComponent(
      "baseFabExtendedAtomsCircle10"
    ),

    rectangle28: makeNodeComponent("rectangle28"),
    label11: makeNodeComponent("label11"),
    group442: makeNodeComponent("group442"),
    frame12: makeNodeComponent("frame12"),
    group422: makeNodeComponent("group422"),
    frame22: makeNodeComponent("frame22"),
    iconBack2: makeNodeComponent("iconBack2"),
    icroundKeyboardBackspace2: makeNodeComponent("icroundKeyboardBackspace2"),
    buttons12: makeNodeComponent("buttons12"),
    label12: makeNodeComponent("label12"),
    landingPage010213: makeNodeComponent("landingPage010213"),
    ωAtomsSystemBarDark8: makeNodeComponent("ωAtomsSystemBarDark8"),
    rectangle29: makeNodeComponent("rectangle29"),
    // Metadata about props expected for Plasmic_5
    internalVariantProps: Plasmic_5__VariantProps,
    internalArgProps: Plasmic_5__ArgProps
  }
);

export default Plasmic_5;
/* prettier-ignore-end */
