// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o1vPdgLXqG8oxG6Tov2xRt
// Component: rey17QXadj
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_empty_project_mobile_first.module.css"; // plasmic-import: o1vPdgLXqG8oxG6Tov2xRt/projectcss
import * as sty from "./Plasmic_6.module.css"; // plasmic-import: rey17QXadj/css
import BaseFabExtendedAtomsDiamondIcon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond"; // plasmic-import: mlbS78wvC-2/icon
import BaseFabExtendedAtomsDiamond2Icon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond2"; // plasmic-import: atsv3shmpol/icon
import MaskIcon from "./icons/PlasmicIcon__Mask"; // plasmic-import: PW6nB-ZdXb6/icon

export const Plasmic_6__VariantProps = new Array();

export const Plasmic_6__ArgProps = new Array();

function Plasmic_6__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"iPhone849"}
            data-plasmic-override={overrides.iPhone849}
            className={classNames(defaultcss.all, sty.iPhone849)}
          >
            {false ? (
              <div
                data-plasmic-name={"icons9"}
                data-plasmic-override={overrides.icons9}
                className={classNames(defaultcss.all, sty.icons9)}
              >
                <div
                  data-plasmic-name={"overflow9"}
                  data-plasmic-override={overrides.overflow9}
                  className={classNames(defaultcss.all, sty.overflow9)}
                />

                <div
                  data-plasmic-name={"icon39"}
                  data-plasmic-override={overrides.icon39}
                  className={classNames(defaultcss.all, sty.icon39)}
                />

                <div
                  data-plasmic-name={"icon29"}
                  data-plasmic-override={overrides.icon29}
                  className={classNames(defaultcss.all, sty.icon29)}
                />

                <div
                  data-plasmic-name={"icon19"}
                  data-plasmic-override={overrides.icon19}
                  className={classNames(defaultcss.all, sty.icon19)}
                />
              </div>
            ) : null}

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___6W93S
              )}
            >
              {"Ensuring you’re always in control"}
            </div>

            <a
              data-plasmic-name={"buttons13"}
              data-plasmic-override={overrides.buttons13}
              className={classNames(defaultcss.all, sty.buttons13)}
              href={"/9"}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape10"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape10
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape10
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle10"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle10
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle10
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare10"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare10
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare10
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle30"}
                        data-plasmic-override={overrides.rectangle30}
                        className={classNames(defaultcss.all, sty.rectangle30)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamondIcon
                    className={classNames(defaultcss.all, sty.svg__sXxKz)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle11"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle11}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle11
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle31"}
                    data-plasmic-override={overrides.rectangle31}
                    className={classNames(defaultcss.all, sty.rectangle31)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label13"}
                data-plasmic-override={overrides.label13}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label13
                )}
              >
                {"begin your journey"}
              </div>
            </a>

            <p.Stack
              as={"div"}
              data-plasmic-name={"group443"}
              data-plasmic-override={overrides.group443}
              hasGap={true}
              className={classNames(defaultcss.all, sty.group443)}
            >
              <div
                data-plasmic-name={"frame13"}
                data-plasmic-override={overrides.frame13}
                className={classNames(defaultcss.all, sty.frame13)}
              />

              <div
                data-plasmic-name={"frame23"}
                data-plasmic-override={overrides.frame23}
                className={classNames(defaultcss.all, sty.frame23)}
              />

              <div
                data-plasmic-name={"group423"}
                data-plasmic-override={overrides.group423}
                className={classNames(defaultcss.all, sty.group423)}
              />
            </p.Stack>

            <div
              data-plasmic-name={"buttons14"}
              data-plasmic-override={overrides.buttons14}
              className={classNames(defaultcss.all, sty.buttons14)}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape11"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape11
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape11
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle11"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle11
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle11
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare11"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare11
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare11
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle32"}
                        data-plasmic-override={overrides.rectangle32}
                        className={classNames(defaultcss.all, sty.rectangle32)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamond2Icon
                    className={classNames(defaultcss.all, sty.svg__zh5NZ)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle12"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle12}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle12
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle33"}
                    data-plasmic-override={overrides.rectangle33}
                    className={classNames(defaultcss.all, sty.rectangle33)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label14"}
                data-plasmic-override={overrides.label14}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label14
                )}
              >
                {"SIGN IN "}
              </div>
            </div>

            <div
              data-plasmic-name={"iconBack3"}
              data-plasmic-override={overrides.iconBack3}
              className={classNames(defaultcss.all, sty.iconBack3)}
            >
              <div
                data-plasmic-name={"icroundKeyboardBackspace3"}
                data-plasmic-override={overrides.icroundKeyboardBackspace3}
                className={classNames(
                  defaultcss.all,
                  sty.icroundKeyboardBackspace3
                )}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__gcQxH
              )}
            >
              {
                "Take full control of your data to build your private safe space that adapts to your needs"
              }
            </div>

            <div
              data-plasmic-name={"asset2"}
              data-plasmic-override={overrides.asset2}
              className={classNames(defaultcss.all, sty.asset2)}
            />

            {false ? (
              <div
                data-plasmic-name={"ωAtomsSystemBarDark9"}
                data-plasmic-override={overrides.ωAtomsSystemBarDark9}
                className={classNames(defaultcss.all, sty.ωAtomsSystemBarDark9)}
              >
                <div
                  data-plasmic-name={"rectangle34"}
                  data-plasmic-override={overrides.rectangle34}
                  className={classNames(defaultcss.all, sty.rectangle34)}
                />

                <MaskIcon
                  className={classNames(defaultcss.all, sty.svg___6440)}
                  role={"img"}
                />
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "iPhone849",
    "icons9",
    "overflow9",
    "icon39",
    "icon29",
    "icon19",
    "buttons13",
    "baseFabExtendedFabExtendedMasterShape10",
    "baseFabExtendedAtomsSquircle10",
    "baseSurfaceShapeAtomsSquare10",
    "rectangle30",
    "baseFabExtendedAtomsCircle11",
    "rectangle31",
    "label13",
    "group443",
    "frame13",
    "frame23",
    "group423",
    "buttons14",
    "baseFabExtendedFabExtendedMasterShape11",
    "baseFabExtendedAtomsSquircle11",
    "baseSurfaceShapeAtomsSquare11",
    "rectangle32",
    "baseFabExtendedAtomsCircle12",
    "rectangle33",
    "label14",
    "iconBack3",
    "icroundKeyboardBackspace3",
    "asset2",
    "ωAtomsSystemBarDark9",
    "rectangle34"
  ],

  iPhone849: [
    "iPhone849",
    "icons9",
    "overflow9",
    "icon39",
    "icon29",
    "icon19",
    "buttons13",
    "baseFabExtendedFabExtendedMasterShape10",
    "baseFabExtendedAtomsSquircle10",
    "baseSurfaceShapeAtomsSquare10",
    "rectangle30",
    "baseFabExtendedAtomsCircle11",
    "rectangle31",
    "label13",
    "group443",
    "frame13",
    "frame23",
    "group423",
    "buttons14",
    "baseFabExtendedFabExtendedMasterShape11",
    "baseFabExtendedAtomsSquircle11",
    "baseSurfaceShapeAtomsSquare11",
    "rectangle32",
    "baseFabExtendedAtomsCircle12",
    "rectangle33",
    "label14",
    "iconBack3",
    "icroundKeyboardBackspace3",
    "asset2",
    "ωAtomsSystemBarDark9",
    "rectangle34"
  ],

  icons9: ["icons9", "overflow9", "icon39", "icon29", "icon19"],
  overflow9: ["overflow9"],
  icon39: ["icon39"],
  icon29: ["icon29"],
  icon19: ["icon19"],
  buttons13: [
    "buttons13",
    "baseFabExtendedFabExtendedMasterShape10",
    "baseFabExtendedAtomsSquircle10",
    "baseSurfaceShapeAtomsSquare10",
    "rectangle30",
    "baseFabExtendedAtomsCircle11",
    "rectangle31",
    "label13"
  ],

  baseFabExtendedFabExtendedMasterShape10: [
    "baseFabExtendedFabExtendedMasterShape10",
    "baseFabExtendedAtomsSquircle10",
    "baseSurfaceShapeAtomsSquare10",
    "rectangle30",
    "baseFabExtendedAtomsCircle11",
    "rectangle31"
  ],

  baseFabExtendedAtomsSquircle10: [
    "baseFabExtendedAtomsSquircle10",
    "baseSurfaceShapeAtomsSquare10",
    "rectangle30"
  ],

  baseSurfaceShapeAtomsSquare10: [
    "baseSurfaceShapeAtomsSquare10",
    "rectangle30"
  ],

  rectangle30: ["rectangle30"],
  baseFabExtendedAtomsCircle11: ["baseFabExtendedAtomsCircle11", "rectangle31"],
  rectangle31: ["rectangle31"],
  label13: ["label13"],
  group443: ["group443", "frame13", "frame23", "group423"],
  frame13: ["frame13"],
  frame23: ["frame23"],
  group423: ["group423"],
  buttons14: [
    "buttons14",
    "baseFabExtendedFabExtendedMasterShape11",
    "baseFabExtendedAtomsSquircle11",
    "baseSurfaceShapeAtomsSquare11",
    "rectangle32",
    "baseFabExtendedAtomsCircle12",
    "rectangle33",
    "label14"
  ],

  baseFabExtendedFabExtendedMasterShape11: [
    "baseFabExtendedFabExtendedMasterShape11",
    "baseFabExtendedAtomsSquircle11",
    "baseSurfaceShapeAtomsSquare11",
    "rectangle32",
    "baseFabExtendedAtomsCircle12",
    "rectangle33"
  ],

  baseFabExtendedAtomsSquircle11: [
    "baseFabExtendedAtomsSquircle11",
    "baseSurfaceShapeAtomsSquare11",
    "rectangle32"
  ],

  baseSurfaceShapeAtomsSquare11: [
    "baseSurfaceShapeAtomsSquare11",
    "rectangle32"
  ],

  rectangle32: ["rectangle32"],
  baseFabExtendedAtomsCircle12: ["baseFabExtendedAtomsCircle12", "rectangle33"],
  rectangle33: ["rectangle33"],
  label14: ["label14"],
  iconBack3: ["iconBack3", "icroundKeyboardBackspace3"],
  icroundKeyboardBackspace3: ["icroundKeyboardBackspace3"],
  asset2: ["asset2"],
  ωAtomsSystemBarDark9: ["ωAtomsSystemBarDark9", "rectangle34"],
  rectangle34: ["rectangle34"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_6__ArgProps,
      internalVariantPropNames: Plasmic_6__VariantProps
    });

    return Plasmic_6__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_6";
  } else {
    func.displayName = `Plasmic_6.${nodeName}`;
  }
  return func;
}

export const Plasmic_6 = Object.assign(
  // Top-level Plasmic_6 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iPhone849: makeNodeComponent("iPhone849"),
    icons9: makeNodeComponent("icons9"),
    overflow9: makeNodeComponent("overflow9"),
    icon39: makeNodeComponent("icon39"),
    icon29: makeNodeComponent("icon29"),
    icon19: makeNodeComponent("icon19"),
    buttons13: makeNodeComponent("buttons13"),
    baseFabExtendedFabExtendedMasterShape10: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape10"
    ),

    baseFabExtendedAtomsSquircle10: makeNodeComponent(
      "baseFabExtendedAtomsSquircle10"
    ),

    baseSurfaceShapeAtomsSquare10: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare10"
    ),

    rectangle30: makeNodeComponent("rectangle30"),
    baseFabExtendedAtomsCircle11: makeNodeComponent(
      "baseFabExtendedAtomsCircle11"
    ),

    rectangle31: makeNodeComponent("rectangle31"),
    label13: makeNodeComponent("label13"),
    group443: makeNodeComponent("group443"),
    frame13: makeNodeComponent("frame13"),
    frame23: makeNodeComponent("frame23"),
    group423: makeNodeComponent("group423"),
    buttons14: makeNodeComponent("buttons14"),
    baseFabExtendedFabExtendedMasterShape11: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape11"
    ),

    baseFabExtendedAtomsSquircle11: makeNodeComponent(
      "baseFabExtendedAtomsSquircle11"
    ),

    baseSurfaceShapeAtomsSquare11: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare11"
    ),

    rectangle32: makeNodeComponent("rectangle32"),
    baseFabExtendedAtomsCircle12: makeNodeComponent(
      "baseFabExtendedAtomsCircle12"
    ),

    rectangle33: makeNodeComponent("rectangle33"),
    label14: makeNodeComponent("label14"),
    iconBack3: makeNodeComponent("iconBack3"),
    icroundKeyboardBackspace3: makeNodeComponent("icroundKeyboardBackspace3"),
    asset2: makeNodeComponent("asset2"),
    ωAtomsSystemBarDark9: makeNodeComponent("ωAtomsSystemBarDark9"),
    rectangle34: makeNodeComponent("rectangle34"),
    // Metadata about props expected for Plasmic_6
    internalVariantProps: Plasmic_6__VariantProps,
    internalArgProps: Plasmic_6__ArgProps
  }
);

export default Plasmic_6;
/* prettier-ignore-end */
