// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o1vPdgLXqG8oxG6Tov2xRt
// Component: XM0rFp_wDz
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_empty_project_mobile_first.module.css"; // plasmic-import: o1vPdgLXqG8oxG6Tov2xRt/projectcss
import * as sty from "./Plasmic_10.module.css"; // plasmic-import: XM0rFp_wDz/css
import FormShape2Icon from "./icons/PlasmicIcon__FormShape2"; // plasmic-import: f7GqIXlx4T_z/icon
import BaseFabExtendedAtomsDiamondIcon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond"; // plasmic-import: mlbS78wvC-2/icon
import MaskIcon from "./icons/PlasmicIcon__Mask"; // plasmic-import: PW6nB-ZdXb6/icon

export const Plasmic_10__VariantProps = new Array();

export const Plasmic_10__ArgProps = new Array();

function Plasmic_10__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"iPhone851"}
            data-plasmic-override={overrides.iPhone851}
            className={classNames(defaultcss.all, sty.iPhone851)}
          >
            {false ? (
              <div
                data-plasmic-name={"icons12"}
                data-plasmic-override={overrides.icons12}
                className={classNames(defaultcss.all, sty.icons12)}
              >
                <div
                  data-plasmic-name={"overflow12"}
                  data-plasmic-override={overrides.overflow12}
                  className={classNames(defaultcss.all, sty.overflow12)}
                />

                <div
                  data-plasmic-name={"icon312"}
                  data-plasmic-override={overrides.icon312}
                  className={classNames(defaultcss.all, sty.icon312)}
                />

                <div
                  data-plasmic-name={"icon212"}
                  data-plasmic-override={overrides.icon212}
                  className={classNames(defaultcss.all, sty.icon212)}
                />

                <div
                  data-plasmic-name={"icon112"}
                  data-plasmic-override={overrides.icon112}
                  className={classNames(defaultcss.all, sty.icon112)}
                />
              </div>
            ) : null}

            <div
              data-plasmic-name={"iconBack6"}
              data-plasmic-override={overrides.iconBack6}
              className={classNames(defaultcss.all, sty.iconBack6)}
            >
              <div
                data-plasmic-name={"icroundKeyboardBackspace6"}
                data-plasmic-override={overrides.icroundKeyboardBackspace6}
                className={classNames(
                  defaultcss.all,
                  sty.icroundKeyboardBackspace6
                )}
              />
            </div>

            <div
              data-plasmic-name={"textFieldOutlined4"}
              data-plasmic-override={overrides.textFieldOutlined4}
              className={classNames(defaultcss.all, sty.textFieldOutlined4)}
            >
              <FormShape2Icon
                className={classNames(defaultcss.all, sty.svg__kyDjH)}
                role={"img"}
              />

              {false ? (
                <div
                  data-plasmic-name={"assistiveText4"}
                  data-plasmic-override={overrides.assistiveText4}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.assistiveText4
                  )}
                >
                  {"*Required"}
                </div>
              ) : null}
              {false ? (
                <div
                  data-plasmic-name={"trailingIcon4"}
                  data-plasmic-override={overrides.trailingIcon4}
                  className={classNames(defaultcss.all, sty.trailingIcon4)}
                />
              ) : null}

              <div
                data-plasmic-name={"input4"}
                data-plasmic-override={overrides.input4}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.input4
                )}
              >
                {"Diya"}
              </div>

              <div
                data-plasmic-name={"label17"}
                data-plasmic-override={overrides.label17}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label17
                )}
              >
                {"Name"}
              </div>
            </div>

            <div
              data-plasmic-name={"buttons17"}
              data-plasmic-override={overrides.buttons17}
              className={classNames(defaultcss.all, sty.buttons17)}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape14"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape14
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape14
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle14"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle14
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle14
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare17"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare17
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare17
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle44"}
                        data-plasmic-override={overrides.rectangle44}
                        className={classNames(defaultcss.all, sty.rectangle44)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamondIcon
                    className={classNames(defaultcss.all, sty.svg__n1FwD)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle15"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle15}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle15
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle45"}
                    data-plasmic-override={overrides.rectangle45}
                    className={classNames(defaultcss.all, sty.rectangle45)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label18"}
                data-plasmic-override={overrides.label18}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label18
                )}
              >
                {"proceed"}
              </div>
            </div>

            <div
              data-plasmic-name={"box"}
              data-plasmic-override={overrides.box}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box
              )}
            >
              {"What should we \ncall you?"}
            </div>

            {false ? (
              <div
                data-plasmic-name={"ωAtomsSystemBarDark12"}
                data-plasmic-override={overrides.ωAtomsSystemBarDark12}
                className={classNames(
                  defaultcss.all,
                  sty.ωAtomsSystemBarDark12
                )}
              >
                <div
                  data-plasmic-name={"rectangle46"}
                  data-plasmic-override={overrides.rectangle46}
                  className={classNames(defaultcss.all, sty.rectangle46)}
                />

                <MaskIcon
                  className={classNames(defaultcss.all, sty.svg___1Rbgp)}
                  role={"img"}
                />
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "iPhone851",
    "icons12",
    "overflow12",
    "icon312",
    "icon212",
    "icon112",
    "iconBack6",
    "icroundKeyboardBackspace6",
    "textFieldOutlined4",
    "assistiveText4",
    "trailingIcon4",
    "input4",
    "label17",
    "buttons17",
    "baseFabExtendedFabExtendedMasterShape14",
    "baseFabExtendedAtomsSquircle14",
    "baseSurfaceShapeAtomsSquare17",
    "rectangle44",
    "baseFabExtendedAtomsCircle15",
    "rectangle45",
    "label18",
    "box",
    "ωAtomsSystemBarDark12",
    "rectangle46"
  ],

  iPhone851: [
    "iPhone851",
    "icons12",
    "overflow12",
    "icon312",
    "icon212",
    "icon112",
    "iconBack6",
    "icroundKeyboardBackspace6",
    "textFieldOutlined4",
    "assistiveText4",
    "trailingIcon4",
    "input4",
    "label17",
    "buttons17",
    "baseFabExtendedFabExtendedMasterShape14",
    "baseFabExtendedAtomsSquircle14",
    "baseSurfaceShapeAtomsSquare17",
    "rectangle44",
    "baseFabExtendedAtomsCircle15",
    "rectangle45",
    "label18",
    "box",
    "ωAtomsSystemBarDark12",
    "rectangle46"
  ],

  icons12: ["icons12", "overflow12", "icon312", "icon212", "icon112"],
  overflow12: ["overflow12"],
  icon312: ["icon312"],
  icon212: ["icon212"],
  icon112: ["icon112"],
  iconBack6: ["iconBack6", "icroundKeyboardBackspace6"],
  icroundKeyboardBackspace6: ["icroundKeyboardBackspace6"],
  textFieldOutlined4: [
    "textFieldOutlined4",
    "assistiveText4",
    "trailingIcon4",
    "input4",
    "label17"
  ],

  assistiveText4: ["assistiveText4"],
  trailingIcon4: ["trailingIcon4"],
  input4: ["input4"],
  label17: ["label17"],
  buttons17: [
    "buttons17",
    "baseFabExtendedFabExtendedMasterShape14",
    "baseFabExtendedAtomsSquircle14",
    "baseSurfaceShapeAtomsSquare17",
    "rectangle44",
    "baseFabExtendedAtomsCircle15",
    "rectangle45",
    "label18"
  ],

  baseFabExtendedFabExtendedMasterShape14: [
    "baseFabExtendedFabExtendedMasterShape14",
    "baseFabExtendedAtomsSquircle14",
    "baseSurfaceShapeAtomsSquare17",
    "rectangle44",
    "baseFabExtendedAtomsCircle15",
    "rectangle45"
  ],

  baseFabExtendedAtomsSquircle14: [
    "baseFabExtendedAtomsSquircle14",
    "baseSurfaceShapeAtomsSquare17",
    "rectangle44"
  ],

  baseSurfaceShapeAtomsSquare17: [
    "baseSurfaceShapeAtomsSquare17",
    "rectangle44"
  ],

  rectangle44: ["rectangle44"],
  baseFabExtendedAtomsCircle15: ["baseFabExtendedAtomsCircle15", "rectangle45"],
  rectangle45: ["rectangle45"],
  label18: ["label18"],
  box: ["box"],
  ωAtomsSystemBarDark12: ["ωAtomsSystemBarDark12", "rectangle46"],
  rectangle46: ["rectangle46"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_10__ArgProps,
      internalVariantPropNames: Plasmic_10__VariantProps
    });

    return Plasmic_10__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_10";
  } else {
    func.displayName = `Plasmic_10.${nodeName}`;
  }
  return func;
}

export const Plasmic_10 = Object.assign(
  // Top-level Plasmic_10 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iPhone851: makeNodeComponent("iPhone851"),
    icons12: makeNodeComponent("icons12"),
    overflow12: makeNodeComponent("overflow12"),
    icon312: makeNodeComponent("icon312"),
    icon212: makeNodeComponent("icon212"),
    icon112: makeNodeComponent("icon112"),
    iconBack6: makeNodeComponent("iconBack6"),
    icroundKeyboardBackspace6: makeNodeComponent("icroundKeyboardBackspace6"),
    textFieldOutlined4: makeNodeComponent("textFieldOutlined4"),
    assistiveText4: makeNodeComponent("assistiveText4"),
    trailingIcon4: makeNodeComponent("trailingIcon4"),
    input4: makeNodeComponent("input4"),
    label17: makeNodeComponent("label17"),
    buttons17: makeNodeComponent("buttons17"),
    baseFabExtendedFabExtendedMasterShape14: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape14"
    ),

    baseFabExtendedAtomsSquircle14: makeNodeComponent(
      "baseFabExtendedAtomsSquircle14"
    ),

    baseSurfaceShapeAtomsSquare17: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare17"
    ),

    rectangle44: makeNodeComponent("rectangle44"),
    baseFabExtendedAtomsCircle15: makeNodeComponent(
      "baseFabExtendedAtomsCircle15"
    ),

    rectangle45: makeNodeComponent("rectangle45"),
    label18: makeNodeComponent("label18"),
    box: makeNodeComponent("box"),
    ωAtomsSystemBarDark12: makeNodeComponent("ωAtomsSystemBarDark12"),
    rectangle46: makeNodeComponent("rectangle46"),
    // Metadata about props expected for Plasmic_10
    internalVariantProps: Plasmic_10__VariantProps,
    internalArgProps: Plasmic_10__ArgProps
  }
);

export default Plasmic_10;
/* prettier-ignore-end */
