// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o1vPdgLXqG8oxG6Tov2xRt
// Component: E80Qpv1f1M
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_empty_project_mobile_first.module.css"; // plasmic-import: o1vPdgLXqG8oxG6Tov2xRt/projectcss
import * as sty from "./Plasmic_7.module.css"; // plasmic-import: E80Qpv1f1M/css
import BaseFabExtendedAtomsDiamondIcon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond"; // plasmic-import: mlbS78wvC-2/icon
import BaseFabExtendedAtomsDiamond2Icon from "./icons/PlasmicIcon__BaseFabExtendedAtomsDiamond2"; // plasmic-import: atsv3shmpol/icon
import MaskIcon from "./icons/PlasmicIcon__Mask"; // plasmic-import: PW6nB-ZdXb6/icon

export const Plasmic_7__VariantProps = new Array();

export const Plasmic_7__ArgProps = new Array();

function Plasmic_7__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"iPhone862"}
            data-plasmic-override={overrides.iPhone862}
            className={classNames(defaultcss.all, sty.iPhone862)}
          >
            {false ? (
              <div
                data-plasmic-name={"icons2"}
                data-plasmic-override={overrides.icons2}
                className={classNames(defaultcss.all, sty.icons2)}
              >
                <div
                  data-plasmic-name={"overflow2"}
                  data-plasmic-override={overrides.overflow2}
                  className={classNames(defaultcss.all, sty.overflow2)}
                />

                <div
                  data-plasmic-name={"icon32"}
                  data-plasmic-override={overrides.icon32}
                  className={classNames(defaultcss.all, sty.icon32)}
                />

                <div
                  data-plasmic-name={"icon22"}
                  data-plasmic-override={overrides.icon22}
                  className={classNames(defaultcss.all, sty.icon22)}
                />

                <div
                  data-plasmic-name={"icon12"}
                  data-plasmic-override={overrides.icon12}
                  className={classNames(defaultcss.all, sty.icon12)}
                />
              </div>
            ) : null}

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__hz6H
              )}
            >
              {"Always here, just for you"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__a6ER
              )}
            >
              {
                "We know things can get rough sometimes. \nBut we can work it out here together, anytime."
              }
            </div>

            <div
              data-plasmic-name={"buttons3"}
              data-plasmic-override={overrides.buttons3}
              className={classNames(defaultcss.all, sty.buttons3)}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape2"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape2
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape2
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle2"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle2
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle2
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare2"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare2
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare2
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle5"}
                        data-plasmic-override={overrides.rectangle5}
                        className={classNames(defaultcss.all, sty.rectangle5)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamondIcon
                    className={classNames(defaultcss.all, sty.svg__pvv5C)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle3"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle3}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle3
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle6"}
                    data-plasmic-override={overrides.rectangle6}
                    className={classNames(defaultcss.all, sty.rectangle6)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label3"}
                data-plasmic-override={overrides.label3}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label3
                )}
              >
                {"begin your journey"}
              </div>
            </div>

            <div
              data-plasmic-name={"buttons4"}
              data-plasmic-override={overrides.buttons4}
              className={classNames(defaultcss.all, sty.buttons4)}
            >
              <div
                data-plasmic-name={"baseFabExtendedFabExtendedMasterShape3"}
                data-plasmic-override={
                  overrides.baseFabExtendedFabExtendedMasterShape3
                }
                className={classNames(
                  defaultcss.all,
                  sty.baseFabExtendedFabExtendedMasterShape3
                )}
              >
                {false ? (
                  <div
                    data-plasmic-name={"baseFabExtendedAtomsSquircle3"}
                    data-plasmic-override={
                      overrides.baseFabExtendedAtomsSquircle3
                    }
                    className={classNames(
                      defaultcss.all,
                      sty.baseFabExtendedAtomsSquircle3
                    )}
                  >
                    <div
                      data-plasmic-name={"baseSurfaceShapeAtomsSquare3"}
                      data-plasmic-override={
                        overrides.baseSurfaceShapeAtomsSquare3
                      }
                      className={classNames(
                        defaultcss.all,
                        sty.baseSurfaceShapeAtomsSquare3
                      )}
                    >
                      <div
                        data-plasmic-name={"rectangle7"}
                        data-plasmic-override={overrides.rectangle7}
                        className={classNames(defaultcss.all, sty.rectangle7)}
                      />
                    </div>
                  </div>
                ) : null}
                {false ? (
                  <BaseFabExtendedAtomsDiamond2Icon
                    className={classNames(defaultcss.all, sty.svg___2MKc)}
                    role={"img"}
                  />
                ) : null}

                <div
                  data-plasmic-name={"baseFabExtendedAtomsCircle4"}
                  data-plasmic-override={overrides.baseFabExtendedAtomsCircle4}
                  className={classNames(
                    defaultcss.all,
                    sty.baseFabExtendedAtomsCircle4
                  )}
                >
                  <div
                    data-plasmic-name={"rectangle8"}
                    data-plasmic-override={overrides.rectangle8}
                    className={classNames(defaultcss.all, sty.rectangle8)}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"label4"}
                data-plasmic-override={overrides.label4}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.label4
                )}
              >
                {"SIGN IN"}
              </div>
            </div>

            <div
              data-plasmic-name={"iconBack"}
              data-plasmic-override={overrides.iconBack}
              className={classNames(defaultcss.all, sty.iconBack)}
            >
              <div
                data-plasmic-name={"icroundKeyboardBackspace"}
                data-plasmic-override={overrides.icroundKeyboardBackspace}
                className={classNames(
                  defaultcss.all,
                  sty.icroundKeyboardBackspace
                )}
              />
            </div>

            <div
              data-plasmic-name={"image1"}
              data-plasmic-override={overrides.image1}
              className={classNames(defaultcss.all, sty.image1)}
            />

            {false ? (
              <div
                data-plasmic-name={"ωAtomsSystemBarDark2"}
                data-plasmic-override={overrides.ωAtomsSystemBarDark2}
                className={classNames(defaultcss.all, sty.ωAtomsSystemBarDark2)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(defaultcss.all, sty.rectangle9)}
                />

                <MaskIcon
                  className={classNames(defaultcss.all, sty.svg__edNG)}
                  role={"img"}
                />
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "iPhone862",
    "icons2",
    "overflow2",
    "icon32",
    "icon22",
    "icon12",
    "buttons3",
    "baseFabExtendedFabExtendedMasterShape2",
    "baseFabExtendedAtomsSquircle2",
    "baseSurfaceShapeAtomsSquare2",
    "rectangle5",
    "baseFabExtendedAtomsCircle3",
    "rectangle6",
    "label3",
    "buttons4",
    "baseFabExtendedFabExtendedMasterShape3",
    "baseFabExtendedAtomsSquircle3",
    "baseSurfaceShapeAtomsSquare3",
    "rectangle7",
    "baseFabExtendedAtomsCircle4",
    "rectangle8",
    "label4",
    "iconBack",
    "icroundKeyboardBackspace",
    "image1",
    "ωAtomsSystemBarDark2",
    "rectangle9"
  ],

  iPhone862: [
    "iPhone862",
    "icons2",
    "overflow2",
    "icon32",
    "icon22",
    "icon12",
    "buttons3",
    "baseFabExtendedFabExtendedMasterShape2",
    "baseFabExtendedAtomsSquircle2",
    "baseSurfaceShapeAtomsSquare2",
    "rectangle5",
    "baseFabExtendedAtomsCircle3",
    "rectangle6",
    "label3",
    "buttons4",
    "baseFabExtendedFabExtendedMasterShape3",
    "baseFabExtendedAtomsSquircle3",
    "baseSurfaceShapeAtomsSquare3",
    "rectangle7",
    "baseFabExtendedAtomsCircle4",
    "rectangle8",
    "label4",
    "iconBack",
    "icroundKeyboardBackspace",
    "image1",
    "ωAtomsSystemBarDark2",
    "rectangle9"
  ],

  icons2: ["icons2", "overflow2", "icon32", "icon22", "icon12"],
  overflow2: ["overflow2"],
  icon32: ["icon32"],
  icon22: ["icon22"],
  icon12: ["icon12"],
  buttons3: [
    "buttons3",
    "baseFabExtendedFabExtendedMasterShape2",
    "baseFabExtendedAtomsSquircle2",
    "baseSurfaceShapeAtomsSquare2",
    "rectangle5",
    "baseFabExtendedAtomsCircle3",
    "rectangle6",
    "label3"
  ],

  baseFabExtendedFabExtendedMasterShape2: [
    "baseFabExtendedFabExtendedMasterShape2",
    "baseFabExtendedAtomsSquircle2",
    "baseSurfaceShapeAtomsSquare2",
    "rectangle5",
    "baseFabExtendedAtomsCircle3",
    "rectangle6"
  ],

  baseFabExtendedAtomsSquircle2: [
    "baseFabExtendedAtomsSquircle2",
    "baseSurfaceShapeAtomsSquare2",
    "rectangle5"
  ],

  baseSurfaceShapeAtomsSquare2: ["baseSurfaceShapeAtomsSquare2", "rectangle5"],
  rectangle5: ["rectangle5"],
  baseFabExtendedAtomsCircle3: ["baseFabExtendedAtomsCircle3", "rectangle6"],
  rectangle6: ["rectangle6"],
  label3: ["label3"],
  buttons4: [
    "buttons4",
    "baseFabExtendedFabExtendedMasterShape3",
    "baseFabExtendedAtomsSquircle3",
    "baseSurfaceShapeAtomsSquare3",
    "rectangle7",
    "baseFabExtendedAtomsCircle4",
    "rectangle8",
    "label4"
  ],

  baseFabExtendedFabExtendedMasterShape3: [
    "baseFabExtendedFabExtendedMasterShape3",
    "baseFabExtendedAtomsSquircle3",
    "baseSurfaceShapeAtomsSquare3",
    "rectangle7",
    "baseFabExtendedAtomsCircle4",
    "rectangle8"
  ],

  baseFabExtendedAtomsSquircle3: [
    "baseFabExtendedAtomsSquircle3",
    "baseSurfaceShapeAtomsSquare3",
    "rectangle7"
  ],

  baseSurfaceShapeAtomsSquare3: ["baseSurfaceShapeAtomsSquare3", "rectangle7"],
  rectangle7: ["rectangle7"],
  baseFabExtendedAtomsCircle4: ["baseFabExtendedAtomsCircle4", "rectangle8"],
  rectangle8: ["rectangle8"],
  label4: ["label4"],
  iconBack: ["iconBack", "icroundKeyboardBackspace"],
  icroundKeyboardBackspace: ["icroundKeyboardBackspace"],
  image1: ["image1"],
  ωAtomsSystemBarDark2: ["ωAtomsSystemBarDark2", "rectangle9"],
  rectangle9: ["rectangle9"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_7__ArgProps,
      internalVariantPropNames: Plasmic_7__VariantProps
    });

    return Plasmic_7__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_7";
  } else {
    func.displayName = `Plasmic_7.${nodeName}`;
  }
  return func;
}

export const Plasmic_7 = Object.assign(
  // Top-level Plasmic_7 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    iPhone862: makeNodeComponent("iPhone862"),
    icons2: makeNodeComponent("icons2"),
    overflow2: makeNodeComponent("overflow2"),
    icon32: makeNodeComponent("icon32"),
    icon22: makeNodeComponent("icon22"),
    icon12: makeNodeComponent("icon12"),
    buttons3: makeNodeComponent("buttons3"),
    baseFabExtendedFabExtendedMasterShape2: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape2"
    ),

    baseFabExtendedAtomsSquircle2: makeNodeComponent(
      "baseFabExtendedAtomsSquircle2"
    ),

    baseSurfaceShapeAtomsSquare2: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare2"
    ),

    rectangle5: makeNodeComponent("rectangle5"),
    baseFabExtendedAtomsCircle3: makeNodeComponent(
      "baseFabExtendedAtomsCircle3"
    ),

    rectangle6: makeNodeComponent("rectangle6"),
    label3: makeNodeComponent("label3"),
    buttons4: makeNodeComponent("buttons4"),
    baseFabExtendedFabExtendedMasterShape3: makeNodeComponent(
      "baseFabExtendedFabExtendedMasterShape3"
    ),

    baseFabExtendedAtomsSquircle3: makeNodeComponent(
      "baseFabExtendedAtomsSquircle3"
    ),

    baseSurfaceShapeAtomsSquare3: makeNodeComponent(
      "baseSurfaceShapeAtomsSquare3"
    ),

    rectangle7: makeNodeComponent("rectangle7"),
    baseFabExtendedAtomsCircle4: makeNodeComponent(
      "baseFabExtendedAtomsCircle4"
    ),

    rectangle8: makeNodeComponent("rectangle8"),
    label4: makeNodeComponent("label4"),
    iconBack: makeNodeComponent("iconBack"),
    icroundKeyboardBackspace: makeNodeComponent("icroundKeyboardBackspace"),
    image1: makeNodeComponent("image1"),
    ωAtomsSystemBarDark2: makeNodeComponent("ωAtomsSystemBarDark2"),
    rectangle9: makeNodeComponent("rectangle9"),
    // Metadata about props expected for Plasmic_7
    internalVariantProps: Plasmic_7__VariantProps,
    internalArgProps: Plasmic_7__ArgProps
  }
);

export default Plasmic_7;
/* prettier-ignore-end */
