// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: v3r5FjeHwUDiayAfitwffE
// Component: 5UYP7jjjwlUklV
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_twitter.module.css"; // plasmic-import: v3r5FjeHwUDiayAfitwffE/projectcss
import * as sty from "./PlasmicSpacer.module.css"; // plasmic-import: 5UYP7jjjwlUklV/css

export const PlasmicSpacer__VariantProps = new Array();

export const PlasmicSpacer__ArgProps = new Array();

function PlasmicSpacer__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSpacer__ArgProps,
      internalVariantPropNames: PlasmicSpacer__VariantProps
    });

    return PlasmicSpacer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSpacer";
  } else {
    func.displayName = `PlasmicSpacer.${nodeName}`;
  }
  return func;
}

export const PlasmicSpacer = Object.assign(
  // Top-level PlasmicSpacer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicSpacer
    internalVariantProps: PlasmicSpacer__VariantProps,
    internalArgProps: PlasmicSpacer__ArgProps
  }
);

export default PlasmicSpacer;
/* prettier-ignore-end */
